name: SAST - SonarQube

on:
  workflow_call:
    secrets:
      SQ_URL:
        required: true
      SQ_TOKEN:
        required: true

jobs:
  sonarqube-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: SonarQube Scan
        run: |
          docker run --rm \
            -e SONAR_HOST_URL="${{ secrets.SQ_URL }}" \
            -e SONAR_TOKEN="${{ secrets.SQ_TOKEN }}" \
            -v "$PWD/dirty-python-app:/usr/src" \
            sonarsource/sonar-scanner-cli